### ISSUE TITLE
lock async at 1.5.2

### ISSUE THREAD

**Issue by jonschlinkert** [node-base/base-generators#1]
unfortunately async v2.0 uses lodash, which adds 100-200 ms to load time from the various libs we use. might not seem like much, but it builds up.

I'll be doing this in all libs that use async until we can implement other libraries

**Comment by tunnckoCore** [comment]
Might worth if v2.x does the things faster than v1.x (faster than 200-300ms). Just saying that this also need check :)

**Comment by jonschlinkert** [comment]
perhaps but I'd be surprised. async is one of the most vetted, battle-tested libraries in node.js. But you're right, I'll look into it more. thanks

**Comment by jonschlinkert** [comment]
closing since this is really not an issue
